baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site "
theme = "tapp"

logo = "/images/tapp-logo.png"
footercopyright = "copr texe"

	
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"

[[menu.main]]
    name = "About us"
    url = "/about/"
    weight = 2
    identifier = "about"
	
	

[[menu.main]]
    name = "About Sub 1"
    url = "/about-sub-1/"
    weight = 21
    parent = "about"

[[menu.main]]
    name = "About Sub 2"
    url = "/about-sub-2/"
    weight = 22
    parent = "about"
[[menu.main]]
    name = "About Sub 3"
    url = "/about-sub-3/"
    weight = 23
    parent = "about"
	
[[menu.main]]
    name = "Product and services"
    url = "/product-services/"
    weight = 3
    identifier = "product-services"
	


[[menu.main]]
    name = "product-services Sub 1"
    url = "/product-services-sub-1/"
    weight = 31
    parent = "product-services"

[[menu.main]]
    name = "product-services Sub 2"
    url = "/product-services-sub-2/"
    weight = 32
    parent = "product-services"
[[menu.main]]
    name = "product-services Sub 3"
    url = "/product-services-sub-3/"
    weight = 33
    parent = "product-services"
	
	
[[menu.main]]
    name = "Testimonial"
    url = "/testimonial/"
    weight = 4
    identifier = "testimonial"
[[menu.main]]
    name = "Contact us "
    url = "/contact/"
    weight = 5
    identifier = "contact"
	

[[menu.footernav]]
	name = "E-App "
    url = "/#/"
    weight = 1
	
[[menu.footernav]]
	name = "Life Product Selector and MedSup Quoting App"
    url = "/#/"
    weight = 2
	
[[menu.footernav]]
	name = "Property Inspection App"
    url = "/#/"
    weight = 3
	
[[menu.footernav]]
	name = "iPhone Apploader "
    url = "/#/"
    weight = 4
	
[[menu.footernav]]
	name = "Testimonials"
    url = "/#/"
    weight = 5
	
	
[[menu.footernav]]
	name = "Consulting Services"
    url = "/#/"
    weight = 6
	
[[menu.footernav]]
	name = "Privacy Policy"
    url = "/#/"
    weight = 7
	

[[menu.footersocial]]
	identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "#"
    weight = 1
	
[[menu.footersocial]]
	identifier = "facebook"
    pre = "<i class='fa fa-facebook'></i>"
    url = "#"
    weight = 2
	
[[menu.footersocial]]
	identifier = "linkedin"
    pre = "<i class='fa  fa-linkedin'></i>"
    url = "#"
    weight = 3
	
[[menu.footersocial]]
	identifier = "youtube"
    pre = "<i class='fa fa-youtube'></i>"
    url = "#"
    weight = 4
	
[[menu.footersocial]]
	identifier = "google-plus"
    pre = "<i class='fa fa-google-plus'></i>"
    url = "#"
    weight = 5

	
