baseURL = "/"
languageCode = " "
title = "Tapp Solutions"
theme = "tapp"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
	
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"

[[menu.main]]
    name = "About us"
    url = "/about/"
    weight = 2
    identifier = "about"
	
[[menu.main]]
    name = "About Sub 1"
    url = "/about-sub-1/"
    weight = 21
    parent = "about"

[[menu.main]]
    name = "About Sub 2"
    url = "/about-sub-2/"
    weight = 22
    parent = "about"
[[menu.main]]
    name = "About Sub 3"
    url = "/about-sub-3/"
    weight = 23
    parent = "about"
	
[[menu.main]]
    name = "Product and services"
    url = "/product-services/"
    weight = 3
    identifier = "product-services"
	
[[menu.main]]
    name = "product-services Sub 1"
    url = "/product-services-sub-1/"
    weight = 31
    parent = "product-services"

[[menu.main]]
    name = "product-services Sub 2"
    url = "/product-services-sub-2/"
    weight = 32
    parent = "product-services"
[[menu.main]]
    name = "product-services Sub 3"
    url = "/product-services-sub-3/"
    weight = 33
    parent = "product-services"
	
	
[[menu.main]]
    name = "Testimonial"
    url = "/testimonial/"
    weight = 4
    identifier = "testimonial"
[[menu.main]]
    name = "Contact us "
    url = "/contact/"
    weight = 5
    identifier = "contact"
	

[[menu.footernav]]
	name = "E-App "
    url = "/#/"
    weight = 1
	
[[menu.footernav]]
	name = "Life Product Selector and MedSup Quoting App"
    url = "/#/"
    weight = 2
	
[[menu.footernav]]
	name = "Property Inspection App"
    url = "/#/"
    weight = 3
	
[[menu.footernav]]
	name = "iPhone Apploader "
    url = "/#/"
    weight = 4
	
[[menu.footernav]]
	name = "Testimonials"
    url = "/#/"
    weight = 5
	
	
[[menu.footernav]]
	name = "Consulting Services"
    url = "/#/"
    weight = 6
	
[[menu.footernav]]
	name = "Privacy Policy"
    url = "/#/"
    weight = 7
	

[[menu.footersocial]]
	identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "#"
    weight = 1
	
[[menu.footersocial]]
	identifier = "facebook"
    pre = "<i class='fa fa-facebook'></i>"
    url = "#"
    weight = 2
	
[[menu.footersocial]]
	identifier = "linkedin"
    pre = "<i class='fa  fa-linkedin'></i>"
    url = "#"
    weight = 3
	
[[menu.footersocial]]
	identifier = "youtube"
    pre = "<i class='fa fa-youtube'></i>"
    url = "#"
    weight = 4
	
[[menu.footersocial]]
	identifier = "google-plus"
    pre = "<i class='fa fa-google-plus'></i>"
    url = "#"
    weight = 5
	

[params]
    # Enable the contact form by entering your Formspree.io email
    email = "webuimaker@gmail.com"
	
    copyright = "TAPP SOLUTIONS, LLC. COPYRIGHT 2018. ALL RIGHTS RESERVED. "	
	logo = "/images/tapp-logo.png"
	
    
	
[params.about]
    enable = true
    title = "<span>About</span> Tapp Solutions"
    subtitle = "<p>Tapp Solutions helps Life and P&C companies automate Sales, Claims and Inspections using Mobile Apps. Using our custom mobile applications, Insurance companies can sell higher quality policies faster,  collect payments anywhere, and complete more inspections with less work.</p>"
    buttonText = "learn more"
    buttonUrl = "#"

[params.schedule]
    enable = true
    title = "Want to increase your sales with E-app?"
    subtitle = "On Mobile And Desktop"
    buttonText = "Schedule a phone call or demo"
    buttonUrl = "#"

[params.getInTouch]
    enable = true
    title = "<span>Get In </span>Touch"
    subtitle = "We help agents sell policies faster and easier than ever before using mobile technology. "
    email = "info@tappsolutions.com"
    phone = "(+1) 404-618-0606"
    location = "<p>3423 Piedmont RD NE Atlanta, GA 30305 USA</p>"
	
[params.freeTrial]
    enable = true
    buttonText = "Free Trial of Apps"
    buttonUrl = "#"